### ISSUE TITLE
Problem w/Hero8 - Too many Gopros

### ISSUE THREAD

**Issue by SantaTitular** [JasonFriedman/GoProMatlab#1]
![16426937077079106885623489856049](https://user-images.githubusercontent.com/68435474/150372913-f0d339f7-b725-47ce-a959-b366484fcc0b.jpg)

Hello,

First of, thank you for the effort and the code!

For some reason, when I run the bluetooth option in Mac it works but in Windows I get this problem. Any chance you know what is happening?

**Comment by JasonFriedman** [comment]
There are differences in the way bluetooth is handled in Matlab between PC and Mac.

I think the multiple go pros all have the same name as far as windows is concerned.

But did you try the suggestion given in the error message - specifying instead one of the MAC addresses?

e.g. D0A54F095FE6
